[package]
name = "qxsql"
version = "0.1.1"
edition = "2024"
default-run = "qxsqld"

[lib]
name = "qxsql"
path = "src/lib.rs"

[[bin]]
name = "qxsqld"
path = "src/bin/qxsqld/main.rs"
required-features = ["qxsqld"]

# -----------------------------
# Core library dependencies
# -----------------------------
[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1.89"
anyhow = "1.0"
regex = "1.9"
log = { version = "0.4" }
shvproto = { version = "6.0.1", features = ["serde"] }
shvrpc = { version = "15.0" }

# -----------------------------
# Optional dependencies (used only by the qxsqld binary)
# -----------------------------
shvclient = { git = "https://github.com/silicon-heaven/libshvclient-rs", branch = "main", default-features = false, optional = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "postgres", "chrono"], optional = true }
futures = { version = "0.3.30", optional = true }
futures-util = { version = "0.3.30", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.7.10", features = ["compat"], optional = true }
clap = { version = "4.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
url = { version = "2.2", optional = true }
serde_yaml = { version = "0.9", optional = true }
duration-str = { version = "0.17", optional = true }
flexi_logger = { version = "0.31.8" }

# -----------------------------
# Features
# -----------------------------
[features]
default = []
recchng = [  ]
recchng-smol = [
    "recchng",
    "shvclient/smol",
]
recchng-tokio = [
    "recchng",
    "shvclient/tokio",
]
qxsqld = [
    "recchng-tokio",
    "sqlx",
    "futures",
    "futures-util",
    "tokio",
    "tokio-util",
    "clap",
    "serde_json",
    "url",
    "serde_yaml",
    "duration-str"
]

# -----------------------------
# For local development overrides
# -----------------------------
# [patch."https://github.com/silicon-heaven/libshvproto-rs"]
# shvproto = { path = "../shvrs/libshvproto-rs" }
# [patch."https://github.com/silicon-heaven/libshvclient-rs"]
# shvclient = { path = "../libshvclient-rs" }
