name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "recchng-smol", "recchng-tokio"]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        if [ "${{ matrix.features }}" = "" ]; then
          cargo build --verbose
        else
          cargo build --features "${{ matrix.features }}" --verbose
        fi
    - name: Clippy
      run: |
        if [ "${{ matrix.features }}" = "" ]; then
          cargo clippy --verbose
        else
          cargo clippy --features "${{ matrix.features }}" --verbose
        fi
    - name: Run tests
      run: |
        if [ "${{ matrix.features }}" = "" ]; then
          cargo test --verbose
        else
          cargo test --features "${{ matrix.features }}" --verbose
        fi
